package handler

import (
	"crypto/rand"
	"encoding/hex"
	"strings"

	"github.com/logikraf/logikraf-v2/internal/domain/model"

	"github.com/gofiber/fiber/v3"
	"github.com/logikraf/logikraf-v2/pkg/auth"
)

func generateInviteCode() (string, error) {
	b := make([]byte, 5)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return strings.ToUpper(hex.EncodeToString(b)), nil
}

// ClientByUserID returns the Client record linked to a logged-in user.
func ClientByUserID(userID uint) (*model.Client, error) {
	var c model.Client
	if err := model.DB.Where("user_id = ?", userID).First(&c).Error; err != nil {
		return nil, err
	}
	return &c, nil
}

func GetClients(c fiber.Ctx) error {
	var items []model.Client
	if err := model.DB.Order("created_at desc").Find(&items).Error; err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "failed"})
	}
	return c.JSON(items)
}

func CreateClient(c fiber.Ctx) error {
	var input model.Client
	if err := c.Bind().JSON(&input); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "invalid"})
	}
	code, err := generateInviteCode()
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "failed"})
	}
	input.InviteCode = code
	if err := model.DB.Create(&input).Error; err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "failed"})
	}
	return c.Status(201).JSON(fiber.Map{
		"id":           input.ID,
		"company_name": input.CompanyName,
		"pic_name":     input.PICName,
		"email":        input.Email,
		"phone":        input.Phone,
		"city":         input.City,
		"invite_code":  input.InviteCode,
	})
}

func UpdateClient(c fiber.Ctx) error {
	id := c.Params("id")
	var input model.Client
	if err := c.Bind().JSON(&input); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "invalid"})
	}
	var c1 model.Client
	if err := model.DB.First(&c1, id).Error; err != nil {
		return c.Status(404).JSON(fiber.Map{"error": "not found"})
	}
	c1.CompanyName = input.CompanyName
	c1.PICName = input.PICName
	c1.Email = input.Email
	c1.Phone = input.Phone
	c1.City = input.City
	c1.Address = input.Address
	model.DB.Save(&c1)
	return c.JSON(c1)
}

func DeleteClient(c fiber.Ctx) error {
	id := c.Params("id")
	if err := model.DB.Delete(&model.Client{}, id).Error; err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "failed"})
	}
	return c.SendStatus(204)
}

// RegisterClient lets a client self-register using a one-time invite code
// generated by an admin. Safety: code must exist, be unused, and email must be
// unique. On success the User (role=client) is created and linked to the
// Client record; the invite code is consumed.
func RegisterClient(c fiber.Ctx) error {
	var req struct {
		Name       string `json:"name"`
		Email      string `json:"email"`
		Password   string `json:"password"`
		InviteCode string `json:"invite_code"`
	}
	if err := c.Bind().JSON(&req); err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "invalid"})
	}
	req.Name = strings.TrimSpace(req.Name)
	req.Email = strings.ToLower(strings.TrimSpace(req.Email))
	req.InviteCode = strings.ToUpper(strings.TrimSpace(req.InviteCode))
	if req.Name == "" || req.Email == "" || req.Password == "" || req.InviteCode == "" {
		return c.Status(400).JSON(fiber.Map{"error": "all fields required"})
	}
	if len(req.Password) < 8 {
		return c.Status(400).JSON(fiber.Map{"error": "password too short (min 8 chars)"})
	}

	var client model.Client
	if err := model.DB.Where("invite_code = ?", req.InviteCode).First(&client).Error; err != nil {
		return c.Status(400).JSON(fiber.Map{"error": "invalid invite code"})
	}
	if client.UserID != 0 {
		return c.Status(400).JSON(fiber.Map{"error": "invite code already used"})
	}

	var count int64
	model.DB.Model(&model.User{}).Where("email = ?", req.Email).Count(&count)
	if count > 0 {
		return c.Status(400).JSON(fiber.Map{"error": "email already registered"})
	}

	hashed, err := auth.HashPassword(req.Password)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "failed"})
	}
	user := model.User{
		Name:     req.Name,
		Email:    req.Email,
		Password: string(hashed),
		Role:     "client",
		Tenant:   "logikraf",
	}
	tx := model.DB.Begin()
	if tx.Error != nil {
		return c.Status(500).JSON(fiber.Map{"error": "failed"})
	}
	if err := tx.Create(&user).Error; err != nil {
		tx.Rollback()
		return c.Status(500).JSON(fiber.Map{"error": "failed"})
	}
	if err := tx.Model(&model.Client{}).Where("id = ?", client.ID).Updates(map[string]any{
		"user_id":     user.ID,
		"invite_code": "",
		"email":       req.Email,
	}).Error; err != nil {
		tx.Rollback()
		return c.Status(500).JSON(fiber.Map{"error": "failed"})
	}
	if err := tx.Commit().Error; err != nil {
		return c.Status(500).JSON(fiber.Map{"error": "failed"})
	}
	return c.Status(201).JSON(fiber.Map{"message": "registered", "email": req.Email})
}
